
# cargo-vet audits file

[[audits.cfg-expr]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.15.8 -> 0.16.0"

[[audits.cfg_aliases]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.1.1 -> 0.2.1"

[[audits.miniz_oxide]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.7.2 -> 0.7.4"

[[audits.ppv-lite86]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.2.17 -> 0.2.18"

[[audits.ppv-lite86]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.2.18 -> 0.2.20"

[[audits.proc-macro-crate]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "3.1.0 -> 3.2.0"

[[audits.strum]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.25.0 -> 0.26.3"

[[audits.strum_macros]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.25.3 -> 0.26.4"

[[audits.url]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "2.5.1 -> 2.5.2"

[[audits.utf8parse]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.2.1 -> 0.2.2"

[[audits.version-compare]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.1.1 -> 0.2.0"

[[audits.version_check]]
who = "Sophie Herold <sophie@hemio.de>"
criteria = "safe-to-deploy"
delta = "0.9.4 -> 0.9.5"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2025-07-25"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2025-07-25"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2025-07-25"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2025-07-25"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2025-07-25"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2025-07-25"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2025-07-25"

[[trusted.async-process]]
criteria = "safe-to-deploy"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2021-04-24"
end = "2025-07-25"

[[trusted.async-signal]]
criteria = "safe-to-deploy"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2023-09-28"
end = "2025-07-25"

[[trusted.async-trait]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-23"
end = "2025-07-25"

[[trusted.backtrace]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2023-06-29"
end = "2025-07-25"

[[trusted.byteorder]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-09"
end = "2025-07-25"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2025-07-25"

[[trusted.crossbeam-utils]]
criteria = "safe-to-deploy"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2020-10-12"
end = "2025-07-25"

[[trusted.env_filter]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2024-01-19"
end = "2025-07-25"

[[trusted.env_logger]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-11-24"
end = "2025-07-25"

[[trusted.indexmap]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2020-01-15"
end = "2025-07-25"

[[trusted.is_terminal_polyfill]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2024-05-02"
end = "2025-07-25"

[[trusted.jobserver]]
criteria = "safe-to-deploy"
user-id = 1
start = "2019-03-15"
end = "2025-07-25"

[[trusted.kamadak-exif]]
criteria = "safe-to-deploy"
user-id = 5577 # KAMADA Ken'ichi (kamadak)
start = "2019-12-22"
end = "2025-07-25"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2025-07-25"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2025-07-25"

[[trusted.mutate_once]]
criteria = "safe-to-deploy"
user-id = 5577 # KAMADA Ken'ichi (kamadak)
start = "2019-07-25"
end = "2025-07-25"

[[trusted.paste]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-19"
end = "2025-07-25"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2025-07-25"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2025-07-25"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2025-07-25"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2025-07-25"

[[trusted.same-file]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-16"
end = "2025-07-25"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2025-07-25"

[[trusted.serde_repr]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-26"
end = "2025-07-25"

[[trusted.serde_spanned]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-01-20"
end = "2025-07-25"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2025-07-25"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-07-25"

[[trusted.system-deps]]
criteria = "safe-to-deploy"
user-id = 52034 # Guillaume Desmottes (gdesmott)
start = "2020-06-19"
end = "2025-09-03"

[[trusted.target-lexicon]]
criteria = "safe-to-deploy"
user-id = 696 # Nick Fitzgerald (fitzgen)
start = "2024-07-30"
end = "2025-08-13"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-07-25"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-07-25"

[[trusted.toml]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-12-14"
end = "2025-07-25"

[[trusted.toml_datetime]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-10-21"
end = "2025-07-25"

[[trusted.toml_edit]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2025-07-25"

[[trusted.walkdir]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-09"
end = "2025-07-25"

[[trusted.winapi-util]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2020-01-11"
end = "2025-07-25"

[[trusted.winnow]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2025-07-25"
